spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_shifree?characterEncoding=utf-8
    username: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource
server:
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.qf.pojo

pagehelper:
  helper-dialect: mysql